### ISSUE TITLE
forbid to show the compiling information with "warn_unused_result"

### ISSUE THREAD

**Issue by zhangningbo** [dav/word2vec#2]
When you make, some information with "warn_unused_result" appears.

In file "/src/makefile", you can modify 
             CFLAGS = -lm -pthread -O2 -Wall -funroll-loops
to 
             CFLAGS = -lm -pthread -O2 -Wall -funroll-loops -Wno-unused-result

and then, the fly is gone.

**Comment by arielf** [comment]
Thanks!
Fixed in this PR:  https://github.com/dav/word2vec/pull/8
