### ISSUE TITLE
Downloading text8.gz unexpectedly terminates

### ISSUE THREAD

**Issue by maxsong123** [dav/word2vec#4]
Ex. Terminal screen reads: 

Saving to: '../data/text8.gz'

    [   <=>                                 ] 29,950,984   297KB/s   

After some progress, terminal unexpectedly quits.

**Comment by arielf** [comment]
Thanks for reporting this.

I can't reproduce this (downloading of `text8.gz` works just fine here)
It seems it has nothing to do with `word2vec` (or its demos).  More like networking issues in your particular env.

I think this issue can be closed (as "works for me")
